### ISSUE TITLE
Your "wenhao_plugin" is an outdated version 6 years ago, which is extremely unstable.

### ISSUE THREAD

**Issue by w4454962** [UnryzeC/MemHackAPI#4]
It is recommended to delete it, because the author's technology at that time is very poor.

**Comment by UnryzeC** [comment]
It was added just to support some of its functionality, I have no real interest in the plugin itself nor do I really care about MemHack anymore due to my new project.

So just "removing" it is not an option as it works for those who needed it, if there is a replacement - sure, I will replace it, as long as it retains previous API.
